---
- name: Download NiFi binary
  ansible.builtin.get_url:
    url: "{{ download_mirror_uri }}/nifi/{{ nifi_version }}/nifi-{{ nifi_version }}-bin.zip"
    dest: "/tmp/nifi-{{ nifi_version }}-bin.zip"
    mode: "0644"

- name: Unpack NiFi binary
  ansible.builtin.unarchive:
    remote_src: "yes"
    src: "/tmp/nifi-{{ nifi_version }}-bin.zip"
    dest: "{{ nifi_config_dirs.install }}/"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    creates: "{{ nifi_config_dirs.install }}/nifi-{{ nifi_version }}"

- name: Fix permissions
  ansible.builtin.file:
    path: "{{ nifi_config_dirs.install }}/nifi-{{ nifi_version }}"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    recurse: "yes"

- name: Create NiFi symlink
  ansible.builtin.file:
    src: "nifi-{{ nifi_version }}"
    path: "{{ nifi_config_dirs.home }}"
    state: "link"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    mode: "0755"
  with_items:
    - "{{ nifi_config_dirs.run }}"
    - "{{ nifi_config_dirs.logs }}"

- name: Set NiFi home
  ansible.builtin.copy:
    dest: "/etc/profile.d/nifi-home.sh"
    content: "export NIFI_HOME={{ nifi_config_dirs.home }}"
    mode: "0644"
