---
- name: Prepare system
  ansible.builtin.include_tasks: prepare.yml

- name: Install NiFi
  ansible.builtin.include_tasks: install.yml

- name: Customize NiFi
  ansible.builtin.include_tasks: customize.yml

- name: Run NiFi as system service
  ansible.builtin.include_tasks: run.yml
