---
- name: Install lxml python module
  ansible.builtin.package:
    name: python3-lxml
    state: present

- name: Create NiFi group
  ansible.builtin.group:
    name: "{{ nifi_group }}"
    state: "present"
    system: true

- name: Create NiFi user
  ansible.builtin.user:
    name: "{{ nifi_user }}"
    groups: "{{ nifi_group }}"
    append: true
    state: "present"
    create_home: "no"
    system: true

- name: Check if binaries (tmp) directory exists
  ansible.builtin.stat:
    path: "{{ nifi_config_dirs.binaries }}"
  register: binaries_directory

- name: Create NiFi directories
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: "directory"
    owner: "{{ nifi_user }}"
    group: "{{ nifi_group }}"
    mode: "0755"
  loop: "{{ nifi_config_dirs | dict2items }}"
  when: "item.key != 'binaries' or (item.key == 'binaries' and not binaries_directory.stat.exists)"

- name: Set NiFi home
  ansible.builtin.lineinfile:
    path: "/etc/environment"
    line: "export NIFI_HOME={{ nifi_config_dirs.home }}"
    create: true
    mode: "0644"
