---
- name: Copy systemd template
  ansible.builtin.template:
    src: "templates/nifi.service.j2"
    dest: "/etc/systemd/system/nifi.service"
    mode: "0644"

- name: Re/Start NiFi
  ansible.builtin.service:
    name: "nifi.service"
    state: restarted
    daemon_reload: true
    enabled: true
